batch_size: 1024
beta: 1.0
buffer_size: 20000000
checkpoints_path: null
device: cuda
discount: 0.99
env: antmaze-large-diverse-v2
eval_freq: 50000
group: hiql-antmaze-large-diverse-v2-multiseed-v0
iql_deterministic: false
iql_tau: 0.7
load_model: ''
max_timesteps: 1000000
n_episodes: 100
name: HIQL
normalize: false
normalize_reward: false
project: HIQL
seed: 0
tau: 0.005
